# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0061dda9582b4d3d9b906e1bbfc0eb2233cf704cae063cdbdfafed44a8c6f50c1d496aba888b1282d3a9056b955cdc3475577f5bad7866835d7cc58c625fda5

test:
  secret_key_base: 4de6065cdc20c7867b7d72c975826605b1b0f6c378de636e5d8f74b0061ad0ff26e3b2da622b58d7aa3e53788eeab0901f13b8c0400e78425a55bf2ceebfcf63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
